---
title: "results"
author: "Valentina Cafarelli"
date: "4/25/2021"
output: html_document
---

*Note: see Appendix 2 for code and visualizations*

To assess our model, we test it with data that was not included to train the algorithm. We then compute a number of Confusion Matrices and test it with new tweets from the two users as well with tweets from unrelated users. 

Both based on the Confusion Matrices and on our manual test, we find that our algorithm is able to accurately predict whether a given tweet was more likely tweeted by Boris Johnson or AOC  about 70% of the times.

Moreover, we find that our algorithm is better at predicting tweets by Boris Johnson compared to those by AOC. This is shown by the results in the Confusion Matrices: the chance that the model wrongly attributes a tweet by Boris Johnson to AOC is very low, while the same is not true if we look at the likelihood that the model wrongly attributes a tweet by AOC to Boris Johnson. This could be due to the fact that AOC tweets about a vaster number of topics and that a subset of these are also commonly present in tweets by Boris Johnson; an alternative explanation could use this same argument but with choice of words rather than topics i.e. AOC uses a vaster vocabulary.

In general, the Confusion Matrices predict with accuracy of about 70% (~66% in the first case, 67% in the second case, 70% in the third case; see chunks 5 and 6 in Appendix 2). When testing the model manually, we find a similar level of accuracy: we test 10 tweets (5 by BJ and 5 by AOC) and we find that the model accurately predicts who tweeted each tweet 7 times out of 10 (thus, again, with about 70% accuracy).


When we tested tweets from unrelated users (see chunks 20 in Appendix 2), we notice that the model behaves as expected based on the hypotheses stated above. In fact, since AOC likely uses a wider spectrum of words, many of the tweets were attributed to her by the algorithm. Even Tweets which contain content which would normally be associated with BJ were attributed to AOC, such as for example “Buckingham Palace have released a new picture of Queen Elizabeth in celebration of her 95th birthday”.  In this sense, the model ‘breaks’ when we test it with tweets written by unrelated users.


Lastly, by looking at the most used words by each politician, we find that both Johnson and AOC commonly commented on a key international issue: “COVID” was one of the most used words in tweets from Ocasio-Cortez and “pandemic” was one of Boris Johnson’s most used words. However, there were also considerable differences which allowed our algorithm to predict which user a Tweet came from. For instance, Johnson is prime minister of the UK and so one of the most common words in his tweets is UK. Almost certainly, if a tweet contains “ UK “, it was issued by Johnson. 